BestRestaurant/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext
  {
    public DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Review> Reviews { get; set; }

    public BestRestaurantContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurant/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Name { get; set; }
    public List<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurant/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public int CuisineId { get; set; }
    public Cuisine Cuisine { get; set; } 
    public List<Review> Reviews { get; set; }
  }
}

BestRestaurant/Models/Review.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Review
  {
    public int ReviewId { get; set; }
    public string Author { get; set; }
    public string ReviewBody { get; set; }
    public int Stars { get; set; }
    public int RestaurantId { get; set; }
    public Restaurant Restaurant { get; set; }  
  }
}

BestRestaurant/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    
    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines
                                  .Include(cuisine => cuisine.Restaurants)
                                  .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View (thisCuisine);
    }

  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

BestRestaurant/Controllers/ReviewsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class ReviewsController : Controller
  {
    private readonly BestRestaurantContext _db;

    public ReviewsController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
                                  .Include(restaurant => restaurant.Reviews)
                                  .FirstOrDefault(res => res.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Create(int id)
    {
      Review review = new Review();
      review.RestaurantId = id;
      return View(review);
    }

    [HttpPost]
    public ActionResult Create (Review review)
    {      
      _db.Reviews.Add(review);
      _db.SaveChanges();
      Restaurant thisRestaurant = _db.Restaurants
                                  .Include(restaurant => restaurant.Reviews)
                                  .FirstOrDefault(res => res.RestaurantId == review.RestaurantId);
      return View("Index", thisRestaurant);
    }
  }
}

BestRestaurant/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Add A New Cuisine</h2>

@using (Html.BeginForm())
{
  <p id="form">@Html.LabelFor(model => model.Name)</p>
  <p id="form">@Html.TextBoxFor(model => model.Name)</p>

  <input type="submit" value="Add new Cuisine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurant/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine
@using BestRestaurant.Models

<h1>@Model.Name</h1>

@if (Model.Restaurants.Count == 0) 
{
  <p>There are no restauants in this cuisine</p>
}

@foreach (Restaurant restaurant in Model.Restaurants) 
{
  @Html.ActionLink(@restaurant.Name, "Details", "Restaurants", new {id = restaurant.RestaurantId})<br>
}



@Html.ActionLink($"Add a {Model.Name} restaurant", "Create", "Restaurants")

@Html.ActionLink("All Cuisines", "Index", "Cuisines")

BestRestaurant/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;

<h2>Cuisines</h2>

@if (Model.Count == 0) 
{
  <p>No cuisines have been added yet</p>
}

<ul>
@foreach(Cuisine cuisine in Model) 
{
  <li>@Html.ActionLink(@cuisine.Name, "Details", new {id = cuisine.CuisineId})</li>
}
</ul>

@Html.ActionLink("Add a cuisine", "Create")<br>

@Html.ActionLink("Add a restaurant", "Create", "Restaurants");

BestRestaurant/Views/Home/index.cshtml
@{
  Layout = "_Layout";
}

<h1>Restaurant Reviews</h1>

<p>@Html.ActionLink("See a list of cuisines", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See a list of restaurants", "Index", "Restaurants")</p>

BestRestaurant/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant
@using BestRestaurant.Models

<h2>Add A New Restaurant</h2>
@using (Html.BeginForm())
{
  <p id="form">@Html.LabelFor(model => model.Name)</p>
  <p id="form">@Html.TextBoxFor(model => model.Name)</p>

  @foreach (Cuisine cuisine in ViewBag.CuisineId)
  {
    <p id="form">@Html.LabelFor(model => model.CuisineId, $"{cuisine.Name}")</p>
    <p id="form">@Html.RadioButtonFor(model => model.CuisineId, cuisine.CuisineId)</p>
  }

  <input type="submit" value="Add new Restaurant" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all cuisines", "Index", "Cuisines")</p>

BestRestaurant/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}


@model BestRestaurant.Models.Restaurant;


<h2>Restaurant name: @Model.Name</h2>
<h2>Cuisine: @Model.Cuisine.Name</h2>



@Html.ActionLink("Back to all Cuisines", "Index", "Cuisines")
@Html.ActionLink("Write A Review", "Create", "Reviews", new { id = Model.RestaurantId })

BestRestaurant/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3> No restaurants have been added </h3>
}
else
{
  <ul>
  @foreach (Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId}) | @restaurant.Cuisine.Name </li>
  }
  </ul>
}

@Html.ActionLink("Add new restaurant", "Create", "Restaurants")

BestRestaurant/Views/Reviews/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Review
@using BestRestaurant.Models



<h2>Write A Review</h2>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Author)
  @Html.TextBoxFor(model => model.Author)
  @Html.LabelFor(model => model.Stars)
  @Html.TextBoxFor(model => model.Stars)
  @Html.LabelFor(model => model.ReviewBody)
  @Html.TextBoxFor(model => model.ReviewBody)
  @Html.Hidden("RestaurantId", Model.RestaurantId)
  
  <input type="submit" value="Submit Review" class="btn btn-default" />
}
@* <p>@Html.ActionLink("All reviews for ", "Index", "Cuisines")</p> *@

BestRestaurant/Views/Reviews/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model BestRestaurant.Models.Restaurant

<h2>Reviews for @Model.Name</h2>

<ul>
@foreach(Review review in Model.Reviews)
{
  <li>@review.Stars</li>
}
</ul>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants</title>
    <link 
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
  <div class="jumbotron">
      <h1 class="display-4">Best Restaurants</h1>
      <p class="lead">A place to browse and post restaurant reviews, organized by cuisine</p>
      <hr class="my-4">
      <p class="lead">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              @Html.ActionLink("All Cuisines", "Index", "Cuisines")<br>
            </li>
            <li class="nav-item active">
              @Html.ActionLink("All Restaurants", "Index", "Restaurants")<br>
            </li>
            <li class="nav-item active">
              @Html.ActionLink("Add A Restaurant", "Create", "Restaurants")<br>
            </li>
            <li class="nav-item active">
              @Html.ActionLink("Add A Cuisine", "Create", "Cuisines")<br>
            </li>
          </ul>
        </div>
      </nav>
      </p>
    </div>
    @RenderBody()
  </body>
</html>